name: Java CI with SpotBugs
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: My first step - check out repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Set up gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 7.6

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Run SpotBugs
        run: |
          ./gradlew spotbugsMain

#name: Java CI with SpotBugs
#
#on: [push, pull_request]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml
#
#      - name: Run SpotBugs
#        uses: spotbugs/spotbugs-github-action@v1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          level: high
#          path: "*/target/*.jar"
