name: Java CI with SpotBugs
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: My first step - check out repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Generate gradle wrapper
        run: gradle wrapper --gradle-version=7.6

      - name: Execute Gradle build and SpotBugs
        run: ./gradlew build