name: Java CI with SpotBugs
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: My first step - check out repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Set up gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 7.6

      - name: Execute Gradle build and SpotBugs
        run: ./gradlew build